apiVersion: v1
kind: Service
metadata:
  name: proxy-public2
  namespace: kubernetes-jupyterhub
spec:
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8081
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.0.2.127
