---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: my-metallb-config
  namespace: metallb-system
spec:
  addresses:
  - 172.31.43.211-172.31.43.221
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: my-metallb-config
  namespace: metallb-system
spec:
  ipAddressPools:
    - my-metallb-config
